version: '3.8'
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 15432:${DB_PORT}
  redis:
    image: redis:7.2.1
    ports:
      - 16379:${REDIS_PORT}
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./src:/api/src
    ports:
      - 18088:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - db
      - redis
