version: '3.8'
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5433:${DB_PORT}
  redis:
    image: redis:7.2.1
    ports:
      - 6380:${REDIS_PORT}
  app:
    build:
      context: .
      dockerfile: ./images/node/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 8088:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - db
      - redis
